[build]
  command = "npm run build"
  publish = "dist"

# Permitir validaci√≥n ACME para certificados SSL
[[redirects]]
  from = "/.well-known/*"
  to = "/.well-known/:splat"
  status = 200

# Proxy para redirigir /next al segundo proyecto
[[redirects]]
  from = "/next/*"
  to = "https://neon-pika-de5689.netlify.app/:splat"
  status = 200
  force = false
